[evm.rinkeby]
http-endpoint = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://rinkeby.infura.io/ws/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://rinkeby.etherscan.io"
chain-id = 4
private-key = "$RINKEBY_PRIVATE_KEY"

[[evm.rinkeby.contracts]]
contract = "Tornado"
address = "0x626FEc5Ffa7Bf1EE8CEd7daBdE545630473E3ABb"
deployed-at = 8896800
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0.05
withdraw-gaslimit = "0x350000"
