[package]
name = "webb-relayer-config"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webb-relayer-store = { path = "../relayer-store" }
webb-relayer-types = { path = "../relayer-types" }
webb-relayer-utils = { path = "../relayer-utils" }
eth2_to_substrate_relay = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
tracing = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
serde_json = { workspace = true }
webb = { workspace = true }
# Used by ethers (but we need it to be vendored with the lib).
native-tls = { workspace = true, optional = true }
webb-proposals = { workspace = true }
ethereum-types = { workspace = true }
glob = { workspace = true }
serde_path_to_error = { workspace = true }

structopt = { version = "^0.3", features = ["paw"], optional = true }
directories-next = { version = "^2.0", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["parking_lot", "env-filter"], optional = true }

[features]
default = ["evm-runtime", "substrate-runtime", "cli"]
cli = [
    "evm-runtime",
    "substrate-runtime",
    "anyhow",
    "tracing-subscriber",
    "structopt",
    "directories-next"
]
evm-runtime = ["webb/evm-runtime", "webb-proposals/evm"]
substrate-runtime = ["webb/substrate-runtime", "webb-proposals/substrate"]
integration-tests = ["tracing-subscriber/json"]
<<<<<<< HEAD
eth2 = ["eth2_to_substrate_relay"]
=======
>>>>>>> 09e4e0f19c541d746b3ca5f2b113c39e9479a8f7
