# Block which represents properties for a network
[evm.athena]
# The name that the chain is indexed on, for linkable anchors
name = "athena"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$ATHENA_HTTP_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$ATHENA_WS_URL"
# chain specific id from evm opcode
chain-id = 5002
# The Private Key of this account on this network
# the format is more dynamic here:
# 1. if it starts with '0x' then this would be raw (64 bytes) hex encoded
#    private key.
#    Example: 0x8917174396171783496173419137618235192359106130478137647163400318
#
# 2. if it starts with '$' then it would be considered as an Enviroment variable
#    of a hex-encoded private key.
#    Example: $RINKEBY_PRIVATE_KEY
#
# 3. if it starts with '> ' then it would be considered as a command that
#    the relayer would execute and the output of this command would be the
#    hex encoded private key.
#    Example: > ./getKey.sh rinkeby-privatekey
#
# 4. if it doesn't contains special characters and has 12 or 24 words in it
#    then we should process it as a mnemonic string: 'word two three four ...'
private-key = "$ATHENA_PRIVATE_KEY"

tx-queue = { max-sleep-interval = 1500 }
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.athena.contracts]]
# The contract can be one of these values
# - Anchor (Fixed Anchor)
# - VAnchor (Variable Anchor)
# - SignatureBridge
contract = "Anchor"
# The address of the contract
address = "0xcd75Ad7AC9C9325105f798c476E84176648F391A"
# The deployed block number of the contract. When a relayer does not have information for
# this contract in its store, it will start to sync and query for relevant historical data
# starting at this block number
deployed-at = 1
# The minimum size configured for deposit / withdraw on the contract
size = 1
# Configuration for the events watcher of this contract. The events-watcher can be switched on/off
# and the polling interval specifies the period of time (in ms) that the events-watcher thread
# will wait before issuing another query for new events.
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
# Configuration related to withdraw (for private transaction relaying)
#    - withdraw-gasLimit: Value which specifies the maximum amount of gas which will be used when
#                         submitting a withdraw transaction
#    - withdraw-fee-percentage: Value which specifies the fees that this relayer will collect upon
#                               submitting a withdraw transaction
withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }
# Entries for this anchor contract's connected edges.
# These fields are used to determine the generation of AnchorUpdate proposals
linked-anchors = [
  { chain = "hermes", address = "0xbfce6B877Ebff977bB6e80B24FbBb7bC4eBcA4df" },
  { chain = "demeter", address = "0x4e3df2073bf4b43B9944b8e5A463b1E185D6448C"},
]
# Proposal signing backend can have a value of "Mocked" or the name of the DKG configuration.
# When the type is "Mocked", the supplied private-key will sign any proposed updates and submit
# the signed proposals to the configured SignatureBridge of the relevant chains.
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.athena.contracts]]
contract = "Anchor"
address = "0x3d3955aAe5Bdf9E6547A140Baad4BC57Fa4EBA17"
deployed-at = 1
size = 0.01
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }
linked-anchors = [
  { chain = "hermes", address = "0xaC361518Bb9535D0E3172DC45a4e56d71a7FDFc4" },
  { chain = "demeter", address = "0x91eB86019FD8D7c5a9E31143D422850A13F670A3"},
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.athena.contracts]]
contract = "VAnchor"
address = "0xFEe587E68c470DAE8147B46bB39fF230A29D4769"
deployed-at = 1
size = 0.01
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }
linked-anchors = [
  { chain = "hermes", address = "0xb824C5F99339C7E486a1b452B635886BE82bc8b7" },
  { chain = "demeter", address = "0xdB587ef6aaA16b5719CDd3AaB316F0E70473e9Be"},
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.athena.contracts]]
contract = "SignatureBridge"
address = "0x51a240271AB8AB9f9a21C82d9a85396b704E164d"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
