# Block which represents properties for a network
[evm.hermes]
# The name that the chain is indexed on, for linkable anchors
name = "hermes"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$HERMES_HTTP_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$HERMES_WS_URL"
# chain specific id from evm opcode
chain-id = 5001
# The Private Key of this account on this network
# the format is more dynamic here:
# 1. if it starts with '0x' then this would be raw (64 bytes) hex encoded
#    private key.
#    Example: 0x8917174396171783496173419137618235192359106130478137647163400318
#
# 2. if it starts with '$' then it would be considered as an Enviroment variable
#    of a hex-encoded private key.
#    Example: $RINKEBY_PRIVATE_KEY
#
# 3. if it starts with '> ' then it would be considered as a command that
#    the relayer would execute and the output of this command would be the
#    hex encoded private key.
#    Example: > ./getKey.sh rinkeby-privatekey
#
# 4. if it doesn't contains special characters and has 12 or 24 words in it
#    then we should process it as a mnemonic string: 'word two three four ...'
private-key = "$HERMES_PRIVATE_KEY"
tx-queue = { max-sleep-interval = 1500 }
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.hermes.contracts]]
# The contract can be one of these values
# - Anchor (Fixed Anchor)
# - VAnchor (Variable Anchor)
# - SignatureBridge
contract = "VAnchor"
# The address of the contract
address = "0x510C6297cC30A058F41eb4AF1BFC9953EaD8b577"
# The deployed block number of the contract. When a relayer does not have information for
# this contract in its store, it will start to sync and query for relevant historical data
# starting at this block number
deployed-at = 1
# The minimum size configured for deposit / withdraw on the contract
size = 0.01
# Configuration for the events watcher of this contract. The events-watcher can be switched on/off
# and the polling interval specifies the period of time (in ms) that the events-watcher thread
# will wait before issuing another query for new events.
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
# Configuration related to withdraw (for private transaction relaying)
#    - withdraw-gasLimit: Value which specifies the maximum amount of gas which will be used when
#                         submitting a withdraw transaction
#    - withdraw-fee-percentage: Value which specifies the fees that this relayer will collect upon
#                               submitting a withdraw transaction
withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }
# Entries for this anchor contract's connected edges.
# These fields are used to determine the generation of AnchorUpdate proposals
linked-anchors = [
  { chain = "athena", address = "0xcbD945E77ADB65651F503723aC322591f3435cC5" },
  { chain = "demeter", address = "0x7758F98C1c487E5653795470eEab6C4698bE541b"},
]
# Proposal signing backend can have a value of "Mocked" or the name of the DKG configuration.
# When the type is "Mocked", the supplied private-key will sign any proposed updates and submit
# the signed proposals to the configured SignatureBridge of the relevant chains.
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.hermes.contracts]]
contract = "SignatureBridge"
address = "0xDe09E74d4888Bc4e65F589e8c13Bce9F71DdF4c7"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
