# Block which represents properties for a network
[evm.goerli]
name = "goerli"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$GOERLI_HTTPS_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$GOERLI_WSS_URL"

explorer = "https://goerli.etherscan.io"
# chain specific id from evm opcode
chain-id = 5

block-confirmations = 2

private-key = "$GOERLI_PRIVATE_KEY"
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.goerli.contracts]]
contract = "VAnchor"
# The address of the contract
address = "0x3a4233bf223622f6571b8543498a62b9e2a3b31f"

deployed-at = 8188267

events-watcher = { enabled = true, polling-interval = 15000 }

linked-anchors = [
  { type = "Evm", chain = "sepolia", chain-id = 11155111, address = "0xb2d1d8d651c53a00e13ea0a363aab575a6886391" },
  { type = "Evm", chain = "mumbai", chain-id = 80001, address = "0xda27349ee55e7c91e1b521ece4c3dcc390383026" },
  { type = "Evm", chain = "optimismtestnet", chain-id = 420, address = "0x9d36b94f245857ec7280415140800dde7642addb" },
  { type = "Evm", chain = "moonbase", chain-id = 1287, address = "0xda27349ee55e7c91e1b521ece4c3dcc390383026"}
]
# proposal-signing-backend = { type = "Mocked", private-key = "$MOCKED_BACKEND_KEY" }
proposal-signing-backend = { type = "DKGNode", node = "tangle" }

[[evm.goerli.contracts]]
contract = "SignatureBridge"
address = "0x773cf4c29a6f2239b9d6ef821d17ab1d705390b9"

deployed-at = 8188232

events-watcher = { enabled = true, polling-interval = 45000, print-progress-interval = 0 }
