# Block which represents properties for a network
[evm.polygontestnet]
name = "polygontestnet"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$POLYGON_TESTNET_HTTPS_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$POLYGON_TESTNET_WSS_URL"

explorer = "https://mumbai.polygonscan.com/"
# chain specific id from evm opcode
chain-id = 80001

block-confirmations = 2

private-key = "$POLYGON_TESTNET_PRIVATE_KEY"
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.polygontestnet.contracts]]

contract = "VAnchor"
# The address of the contract
address = "0x965c94a6e1b713e751164d2ba09aa0306f48ee74"

deployed-at = 29416496

events-watcher = { enabled = true, polling-interval = 15000 }

withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }

linked-anchors = [
  { type = "Evm", chain = "goerli", chain-id = 5, address = "0xbd7e08ef54dfb43e9a86eb12a3ecab7564dee931" },
  { type = "Evm", chain = "sepolia", chain-id = 11155111, address = "0x965c94a6e1b713e751164d2ba09aa0306f48ee74" },
  { type = "Evm", chain = "optimismtestnet", chain-id = 420, address = "0x26a37ce74e5214dd661070601db14a6a8a2fadd9" },
  { type = "Evm", chain = "moonbase", chain-id = 1287, address = "0x75e452a3ce366575f75737438c0fdfe618853946"}
]
# proposal-signing-backend = { type = "Mocked", private-key = "$MOCKED_BACKEND_KEY" }
proposal-signing-backend = { type = "DKGNode", node = "tangle" }

[[evm.polygontestnet.contracts]]
contract = "SignatureBridge"
address = "0x5aaf73ac093fbc429c308e101b73b8b85649dffb"

deployed-at = 29416379

events-watcher = { enabled = true, polling-interval = 45000, print-progress-interval = 0 }
