# Block which represents properties for a network
[evm.sepolia]
name = "sepolia"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$SEPOLIA_HTTPS_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$SEPOLIA_WSS_URL"

explorer = "https://sepolia.etherscan.io"
# chain specific id from evm opcode
chain-id = 11155111

block-confirmations = 2

private-key = "$SEPOLIA_PRIVATE_KEY"
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.sepolia.contracts]]

contract = "VAnchor"
# The address of the contract
address = "0xb2d1d8d651c53a00e13ea0a363aab575a6886391"

deployed-at = 2545802

events-watcher = { enabled = true, polling-interval = 15000 }

withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }

linked-anchors = [
  { type = "Evm", chain = "goerli", chain-id = 5, address = "0x3a4233bf223622f6571b8543498a62b9e2a3b31f" },
  { type = "Evm", chain = "optimismtestnet", chain-id = 420, address = "0x9d36b94f245857ec7280415140800dde7642addb" },
  { type = "Evm", chain = "mumbai", chain-id = 80001, address = "0xda27349ee55e7c91e1b521ece4c3dcc390383026" },
  { type = "Evm", chain = "moonbase", chain-id = 1287, address = "0xda27349ee55e7c91e1b521ece4c3dcc390383026"}
]
# proposal-signing-backend = { type = "Mocked", private-key = "$MOCKED_BACKEND_KEY" }
proposal-signing-backend = { type = "DKGNode", node = "tangle" }

[[evm.sepolia.contracts]]
contract = "SignatureBridge"
address = "0xc99aea79d36227ff5760372f56d37f683954bc2a"

deployed-at = 2478538

events-watcher = { enabled = true, polling-interval = 45000, print-progress-interval = 0 }
