    [substrate.tangle]
    name="tangle"
    enabled=true
    http-endpoint = "https://tangle1.webb.tools"
    ws-endpoint = "wss://tangle1.webb.tools"
    runtime = "DKG"
    suri = "//Alice//stash"
    chain-id = "1080"
    [[substrate.tangle.pallets]]
    pallet = "DKGProposalHandler"
    events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }