[substrate.tangle]
name = "tangle"
enabled = true
http-endpoint = "http://tangle_parachain:9933"
ws-endpoint = "ws://tangle_parachain:9944"
runtime = "DKG"
suri = "$TANGLE_WEBB_RELAYER_SURI"
chain-id = "1080"
[[substrate.tangle.pallets]]
pallet = "DKG"
events-watcher = { enabled = false, polling-interval = 12000, print-progress-interval = 60000 }
[[substrate.tangle.pallets]]
pallet = "DKGProposalHandler"
events-watcher = { enabled = false, polling-interval = 12000, print-progress-interval = 60000 }