version: '3'

services:
  grafana:
    image: grafana/grafana:9.4.7
    network_mode: "host"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data2:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:v2.43.0
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  grafana-data2:
