[evm.kovan]
http-endpoint = "https://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://kovan.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://kovan.etherscan.io"
chain-id = 42
private-key = "$KOVAN_PRIVATE_KEY"

[[evm.kovan.contracts]]
contract = "Anchor"
address = "0xd961d7Cf4d001EC57ff3F6F9F6428B73b7d924Bc"
deployed-at = 28595192
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x8DB24d0Df8cc4CEbF275528f7725E560F50329bf" },
  { chain = "rinkeby", address = "0x99285189A0DA76dce5D3Da6Cf71aD3f2b498DC88" },
  { chain = "goerli", address = "0xC44A4EcAC4f23b6F92485Cb1c90dBEd75a987BC8" },
  { chain = "optimismtest", address = "0xd2e52699762D00f142e2c61280cd87D47B3A3b97" },
  { chain = "arbitrumtest", address = "0x626FEc5Ffa7Bf1EE8CEd7daBdE545630473E3ABb" },
]
