chain-ids = [
    1, # Ethereum Mainnet
    5, # Goerli Testnet
    137, # Polygon Mainnet
    80001, # Polygon Mumbai Testnet
    42161, # Arbitrum One Mainnet
    43113, # Avalance Fuji Testnet
    421613, # Arbitrum Goerli Testnet
    534352, # Scroll Mainnet
    534353, # Scroll Alpha Testnet
    11155111, # Sepolia Testnet
    1284, # Moonbeam Mainnet
    1285, # Moonriver
    1287, # Moonbase Alpha
    5001, # Athena Testnet
    5002, # Hermes Testnet
    5003, # Demeter Testnet
]

# Override the coingecko coin Id for the Moonbase Alpha network
# Since the Moonbase Alpha network is not yet listed on CoinGecko.
# so we use the mainnet coin id instead.
[overrides.1287]
coingecko-coin-id = "moonbeam"

# Override the coingecko coin Id for Arbitrum Goerli Testnet
# Since the Arbitrum Goerli Testnet is not yet listed on CoinGecko.
# so we use the mainnet coin id instead.
[overrides.421613]
coingecko-coin-id = "ethereum"
