export default {
  preset: 'ts-jest/presets/default-esm',
  globals: {
    'ts-jest': {
      useESM: true,
    },
  },
  extensionsToTreatAsEsm: ['.ts'],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@polkadot/rpc-core/(.*).js$': '@polkadot/rpc-core/$1.js',
    '^@polkadot/rpc-core$': '@polkadot/rpc-core/index.js',
    '^@polkadot/rpc-provider/(.*).js$': '@polkadot/rpc-provider/$1.js',
    '^@polkadot/rpc-provider$': '@polkadot/rpc-provider/index.js',
    '^@polkadot/rpc-augment/(.*).js$': '@polkadot/rpc-augment/$1.js',
    '^@polkadot/rpc-augment$': '@polkadot/rpc-augment/index.js',
    '^@polkadot/keyring/(.*).js$': '@polkadot/keyring/$1.js',
    '^@polkadot/keyring$': '@polkadot/keyring/index.js',
    '^@polkadot/api/(.*).js$': '@polkadot/api/$1.js',
    '^@polkadot/api$': '@polkadot/api/index.js',
    '^@polkadot/api-derive/(.*).js$': '@polkadot/api-derive/$1.js',
    '^@polkadot/api-derive$': '@polkadot/api-derive/index.js',
    '^@polkadot/metadata/(.*)/(.*)': '@polkadot/metadata/$1/$2.js',
    '^@polkadot/metadata/decorate$': '@polkadot/metadata/decorate/index.js',
    '^@polkadot/metadata/(.*)': '@polkadot/metadata/$1.js',
    '^@polkadot/metadata$': '@polkadot/metadata/index.js',
    '^@polkadot/networks/(.*).js$': '@polkadot/networks/$1.js',
    '^@polkadot/networks/(.*)': '@polkadot/networks/$1.js',
    '^@polkadot/networks$': '@polkadot/networks/index.js',
    '^@polkadot/types/codec$': '@polkadot/types/codec/index.js',
    '^@polkadot/types/primitive$': '@polkadot/types/primitive/index.js',
    '^@polkadot/types/augment$': '@polkadot/types/augment/index.js',
    '^@polkadot/types/metadata$': '@polkadot/types/metadata/index.js',
    '^@polkadot/types/metadata/decorate$':
      '@polkadot/types/metadata/decorate/index.js',
    '^@polkadot/types/types$': '@polkadot/types/types/index.js',
    '^@polkadot/types/(.*)/(.*)': '@polkadot/types/$1/$2.js',
    '^@polkadot/types/(.*).js$': '@polkadot/types/$1.js',
    '^@polkadot/types/(.*)': '@polkadot/types/$1.js',
    '^@polkadot/types$': '@polkadot/types/index.js',
    '^@polkadot/types-known$': '@polkadot/types-known/index.js',
    '^@polkadot/types-create$': '@polkadot/types-create/index.js',
    '^@polkadot/types-codec$': '@polkadot/types-codec/index.js',
    '^@polkadot/util/(.*).js$': '@polkadot/util/$1.js',
    '^@polkadot/util$': '@polkadot/util/index.js',
    '^@polkadot/util-crypto$': '@polkadot/util-crypto/index.js',
    '^@polkadot/wasm-crypto$': '@polkadot/wasm-crypto/index.js',
    '^@polkadot/wasm-crypto-asmjs/(.*)': '@polkadot/wasm-crypto-asmjs/$1.js',
    '^@polkadot/wasm-crypto-asmjs$': '@polkadot/wasm-crypto-asmjs/empty.js',
    '^@polkadot/wasm-crypto-wasm/(.*)': '@polkadot/wasm-crypto-wasm/$1.js',
    '^@polkadot/wasm-crypto-wasm$': '@polkadot/wasm-crypto-wasm/data.js',
    '^@polkadot/x-global$': '@polkadot/x-global/index.js',
    '^@polkadot/x-randomvalues$': '@polkadot/x-randomvalues/node.js',
    '^@polkadot/x-textdecoder$': '@polkadot/x-textdecoder/node.js',
    '^@polkadot/x-textencoder$': '@polkadot/x-textencoder/node.js',
    '^@polkadot/x-bigint/(.*)': '@polkadot/x-bigint/$1.js',
    '^@polkadot/x-bigint$': '@polkadot/x-bigint/index.js',
    '^@polkadot/x-noble-secp256k1$': '@polkadot/x-noble-secp256k1/index.js',
    '^@polkadot/x-noble-hashes/(.*)': '@polkadot/x-noble-hashes/$1.js',
    '^@polkadot/x-noble-hashes$': '@polkadot/x-noble-hashes/index.js',
    '^@polkadot/x-ws$': '@polkadot/x-ws/node.js',
    '^@polkadot/x-fetch$': '@polkadot/x-fetch/node.js',
  },
  transformIgnorePatterns: [
    '/node_modules/(?!@polkadot|@webb-tools|@babel/runtime/helpers/esm/)',
  ],
  moduleDirectories: ['node_modules'],
};
