[evm.harmonytestnet1]
# Http(s) Endpoint for quick Req/Res
http-endpoint = "https://api.s1.b.hmny.io"
# Websocket Endpoint for long living connections
ws-endpoint = "wss://ws.s1.b.hmny.io"
# Block Explorer
# Optinal, and used for generating clickable links
# for transactions that happens on this chain.
explorer = "https://explorer.pops.one"
# chain specific id.
chain-id = 1666700001
# The Private Key of this account on this network
# the format is more dynamic here:
# 1. if it starts with '0x' then this would be raw (64 bytes) hex encoded
#    private key.
#    Example: 0x8917174396171783496173419137618235192359106130478137647163400318
#
# 2. if it starts with '$' then it would be considered as an Enviroment variable
#    of a hex-encoded private key.
#    Example: $HARMONY_PRIVATE_KEY
#
# 3. if it starts with '> ' then it would be considered as a command that
#    the relayer would execute and the output of this command would be the
#    hex encoded private key.
#    Example: > pass harmony-privatekey
#
# 4. if it doesn't contains special characters and has 12 or 24 words in it
#    then we should process it as a mnemonic string: 'word two three four ...'
private-key = "$HARMONYTESTNET1_PRIVATE_KEY"

# chain contracts
[[evm.harmonytestnet1.contracts]]
# The contract can be one of these values
# - Anchor (tornado protocol)
# - Anchor2 (darkwebb protocol)
# - Bridge
# - GovernanceBravoDelegate
contract = "Tornado"
# The address of this contract on this chain.
address = "0x4c37863bf2642Ba4e8De7e746500C700540119E8"
# the block number where this contract got deployed at.
deployed-at = 13600000
# The size of this contract
# Note: only available for `Anchor` and `Anchor2` contracts.
# and would error otherwise.
size = 0.0000000001
# control the events watcher for this contract
events-watcher = { enabled = true, polling-interval = 3000 }
# The fee percentage that your account will receive when you relay a transaction
# over this chain.
withdraw-fee-percentage = 0.05
# A hex value of the gaslimit when doing a withdraw relay transaction
# on this chain.
withdraw-gaslimit = "0x350000"

[[evm.harmonytestnet1.contracts]]
contract = "Tornado"
address = "0x7cd1F52e5EEdf753e99D945276a725CE533AaD1a"
deployed-at = 12040000
size = 100
events-watcher = { enabled = false, polling-interval = 3000 }
withdraw-fee-percentage = 0.05
withdraw-gaslimit = "0x350000"