{
 "title": "Relayer",
 "time": { "from": "2023-04-17T12:06:23.600Z", "to": "2023-04-17T12:23:15.000Z" },
 "panels": [
  {
   "title": "Total fee earned",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_fee_earned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gas spent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gas_spent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "proposals_processed_evm_tx_queue",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "proposals_processed_substrate_tx_queue",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "proposals_processed_tx_queue", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total amount of data stored",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_amount_of_data_stored", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "evm_transaction_queue_back_off", "legendFormat": "{{__name__}}" },
    { "expr": "bridge_watcher_back_off", "legendFormat": "{{__name__}}" },
    {
     "expr": "substrate_transaction_queue_back_off",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Queue Backoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "evm_transaction_queue_back_off", "legendFormat": "{{__name__}}" },
    {
     "expr": "substrate_transaction_queue_back_off",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Proposals signed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proposals_signed", "legendFormat": "__auto" }
   ]
  }
 ]
}