port = 9955

[substrate.local]
name = "local"
chain-id = 1080
enabled = true
http-endpoint = "http://localhost:9933"
ws-endpoint = "ws://localhost:9944"
runtime = "WebbProtocol"
suri = "//Alice//stash"

[[substrate.local.pallets]]
pallet = "VAnchorBn254"
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 6000 }
