(function() {var implementors = {
"webb_block_poller":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_block_poller/struct.BlockWatcher.html\" title=\"struct webb_block_poller::BlockWatcher\">BlockWatcher</a>"]],
"webb_ew_dkg":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_dkg/struct.DKGMetadataWatcher.html\" title=\"struct webb_ew_dkg::DKGMetadataWatcher\">DKGMetadataWatcher</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_dkg/struct.DKGProposalHandlerWatcher.html\" title=\"struct webb_ew_dkg::DKGProposalHandlerWatcher\">DKGProposalHandlerWatcher</a>"]],
"webb_ew_evm":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_evm/signature_bridge_watcher/struct.SignatureBridgeContractWatcher.html\" title=\"struct webb_ew_evm::signature_bridge_watcher::SignatureBridgeContractWatcher\">SignatureBridgeContractWatcher</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_evm/struct.VAnchorContractWatcher.html\" title=\"struct webb_ew_evm::VAnchorContractWatcher\">VAnchorContractWatcher</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_evm/signature_bridge_watcher/struct.SignatureBridgeGovernanceOwnershipTransferredHandler.html\" title=\"struct webb_ew_evm::signature_bridge_watcher::SignatureBridgeGovernanceOwnershipTransferredHandler\">SignatureBridgeGovernanceOwnershipTransferredHandler</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_evm/struct.AnchorContractWatcher.html\" title=\"struct webb_ew_evm::AnchorContractWatcher\">AnchorContractWatcher</a>"]],
"webb_ew_substrate":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_ew_substrate/struct.SubstrateVAnchorEventWatcher.html\" title=\"struct webb_ew_substrate::SubstrateVAnchorEventWatcher\">SubstrateVAnchorEventWatcher</a>"]],
"webb_light_client_relayer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_light_client_relayer/struct.LightClientWatcher.html\" title=\"struct webb_light_client_relayer::LightClientWatcher\">LightClientWatcher</a>"]],
"webb_price_oracle_backends":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"webb_price_oracle_backends/enum.FiatCurrency.html\" title=\"enum webb_price_oracle_backends::FiatCurrency\">FiatCurrency</a>"]],
"webb_proposal_signing_backends":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_proposal_signing_backends/queue/policy/struct.AlwaysHigherNoncePolicy.html\" title=\"struct webb_proposal_signing_backends::queue::policy::AlwaysHigherNoncePolicy\">AlwaysHigherNoncePolicy</a>"]],
"webb_relayer_config":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_relayer_config/event_watcher/struct.EventsWatcherConfig.html\" title=\"struct webb_relayer_config::event_watcher::EventsWatcherConfig\">EventsWatcherConfig</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_relayer_config/struct.FeaturesConfig.html\" title=\"struct webb_relayer_config::FeaturesConfig\">FeaturesConfig</a>"]],
"webb_relayer_handlers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_relayer_handlers/routes/struct.OptionalRangeQuery.html\" title=\"struct webb_relayer_handlers::routes::OptionalRangeQuery\">OptionalRangeQuery</a>"]],
"webb_relayer_store":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"webb_relayer_store/sled/enum.SledQueueKey.html\" title=\"enum webb_relayer_store::sled::SledQueueKey\">SledQueueKey</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"webb_relayer_store/struct.BridgeKey.html\" title=\"struct webb_relayer_store::BridgeKey\">BridgeKey</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"webb_relayer_store/enum.HistoryStoreKey.html\" title=\"enum webb_relayer_store::HistoryStoreKey\">HistoryStoreKey</a>"]],
"webb_relayer_utils":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"webb_relayer_utils/probe/enum.Kind.html\" title=\"enum webb_relayer_utils::probe::Kind\">Kind</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()