# Block which represents properties for a network
[evm.optimismtestnet]
name = "optimismtestnet"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$OPTIMISM_TESTNET_HTTPS_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$OPTIMISM_TESTNET_WSS_URL"
# Block Explorer
# Optinal, and used for generating clickable links
# for transactions that happen on this chain.
explorer = "https://blockscout.com/optimism/goerli/"
# chain specific id from evm opcode
chain-id = 420

block-confirmations = 2

private-key = "$OPTIMISM_TESTNET_PRIVATE_KEY"
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[evm.optimismtestnet.contracts]]

contract = "VAnchor"
# The address of the contract
address = "0x26a37ce74e5214dd661070601db14a6a8a2fadd9"

deployed-at = 3091427

events-watcher = { enabled = true, polling-interval = 15000 }

withdraw-config = { withdraw-fee-percentage = 0, withdraw-gaslimit = "0x350000" }
# Entries for this anchor contract's connected edges.
# These fields are used to determine the generation of AnchorUpdate proposals
linked-anchors = [
  { type = "Evm", chain = "goerli", chain-id = 5, address = "0xbd7e08ef54dfb43e9a86eb12a3ecab7564dee931" },
  { type = "Evm", chain = "sepolia", chain-id = 11155111, address = "0x965c94a6e1b713e751164d2ba09aa0306f48ee74" },
  { type = "Evm", chain = "polygontestnet", chain-id = 80001, address = "0x965c94a6e1b713e751164d2ba09aa0306f48ee74" },
  { type = "Evm", chain = "moonbase", chain-id = 1287, address = "0x75e452a3ce366575f75737438c0fdfe618853946"}
]
# proposal-signing-backend = { type = "Mocked", private-key = "$MOCKED_BACKEND_KEY" }
proposal-signing-backend = { type = "DKGNode", node = "tangle" }

[[evm.optimismtestnet.contracts]]
contract = "SignatureBridge"
address = "0xb34ec2c9546c6f4f9c1c818b8b66feca781a3073"

deployed-at = 3091344

events-watcher = { enabled = true, polling-interval = 45000, print-progress-interval = 0 }
