[evm.mainnet]
enabled=false
# The name that the chain is indexed on, for linkable anchors
name = "ethereum-mainnet"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "$ETHEREUM_MAINNET_HTTP_URL"
# Websocket Endpoint for long living connections
ws-endpoint = "$ETHEREUM_MAINNET_WS_URL"
# chain specific id from evm opcode
chain-id = 1

[evm.mainnet.block-poller]
# The starting block to listen at.
start-block = 15697112
# Polling interval in milliseconds
polling-interval = 7000
# The maximum blocks per step.
max-blocks-per-step = 1
# The print progress interval.
print-progress-interval = 60_000
# Light client RPC url
light-client-rpc-url = "$ETHEREUM_MAINNET_LIGHT_CLIENT_RPC_URL"