port = 9955

[experimental]
smart-anchor-updates = false
smart-anchor-updates-retries = 3
# etherscan api key
[evm-etherscan.mainnet]
chain-id = 5001
api-key = "$ETHERSCAN_API_KEY"

# The following is the default configuration for Unlisted Assets
[assets]
tTNT = { name = "Test Tangle Token", decimals = 18, price = 0.10 }
TNT = { name = "Tangle Token", decimals = 18, price = 0.10 }
