[evm.shiden]
http-endpoint = "https://shiden.api.onfinality.io/public"
ws-endpoint = "wss://shiden.api.onfinality.io/public"
private-key = "$SHIDEN_PRIVATE_KEY"
reward-address = "$SHIDEN_REWARD_ADDRESS"
chain-id = 336

[[evm.shiden.contracts]]
contract = "Tornado"
address = "0x2B9A7085Afba278BEc6bBfFb399A3C042ED05046"
deployed-at = 566000
size = 10
events-watcher = { enabled = true, polling-interval = 3000 }
withdraw-fee-percentage = 0.05
withdraw-gaslimit = "0x350000"

[[evm.shiden.contracts]]
contract = "Tornado"
address = "0x548555a3275B6fadD5d2B9740a7655cB7f856148"
deployed-at = 568000
size = 1000
events-watcher = { enabled = true, polling-interval = 3000 }
withdraw-fee-percentage = 0.05
withdraw-gaslimit = "0x350000"