[evm.rinkeby]
http-endpoint = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://rinkeby.infura.io/ws/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://rinkeby.etherscan.io"
chain-id = 4
private-key = "$RINKEBY_PRIVATE_KEY"

[[evm.rinkeby.contracts]]
contract = "Anchor"
address = "0x99285189A0DA76dce5D3Da6Cf71aD3f2b498DC88"
deployed-at = 9735243
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x8DB24d0Df8cc4CEbF275528f7725E560F50329bf" },
  { chain = "goerli", address = "0xC44A4EcAC4f23b6F92485Cb1c90dBEd75a987BC8" },
  { chain = "kovan", address = "0xd961d7Cf4d001EC57ff3F6F9F6428B73b7d924Bc" },
  { chain = "optimismtestnet", address = "0xd2e52699762D00f142e2c61280cd87D47B3A3b97" },
  { chain = "arbitrumtestnet", address = "0x626FEc5Ffa7Bf1EE8CEd7daBdE545630473E3ABb" },
]
