[eth2.mainnet]
enabled = true
name = "testnet config"
chain_id = 0
beacon_endpoint = "https://lodestar-mainnet.chainsafe.io"
eth1_endpoint = "https://mainnet.infura.io/v3/ETH1_INFURA_API_KEY"
substrate_endpoint = "localhost:9944"
signer_account_id = "5Dqf9U5dgQ9GLqdfaxXGjpZf9af1sCV8UrnpRgqJPbe3wCwX"
path_to_signer_secret_key = "/tmp/empty/secret_key"
contract_account_id = "NaN"
ethereum_network = "Mainnet"
substrate_network_name = "Testnet"
substrate_network_id = "Testnet"
eth_requests_timeout_seconds = 30
validate_updates = true
verify_bls_signature = true
hashes_gc_threshold = 51000
max_submitted_blocks_by_account = 8000
beacon_rpc_version = "V1_2"
headers_batch_size = 33
interval_between_light_client_updates_submission_in_epochs = 1
max_blocks_for_finalization = 5000
state_requests_timeout_seconds = 1000
sleep_time_on_sync_secs = 0
sleep_time_after_submission_secs = 5