[evm.hermes]
http-endpoint = "http://localhost:5001"
ws-endpoint = "ws://localhost:5001"
chain-id = 5001
private-key = "$HERMES_PRIVATE_KEY"
tx-queue = { max-sleep-interval = 1500 }

[[evm.hermes.contracts]]
contract = "Anchor"
address = "0xbfce6B877Ebff977bB6e80B24FbBb7bC4eBcA4df"
deployed-at = 1
size = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "athena", address = "0xcd75Ad7AC9C9325105f798c476E84176648F391A" },
  { chain = "demeter", address = "0x4e3df2073bf4b43B9944b8e5A463b1E185D6448C" },
]
proposal-signing-backend = { type = "Mocked", private-key = "0x0000000000000000000000000000000000000000000000000000000000000001" }

[[evm.hermes.contracts]]
contract = "Anchor"
address = "0xaC361518Bb9535D0E3172DC45a4e56d71a7FDFc4"
deployed-at = 1
size = 0.01
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "athena", address = "0x3d3955aAe5Bdf9E6547A140Baad4BC57Fa4EBA17" },
  { chain = "demeter", address = "0x91eB86019FD8D7c5a9E31143D422850A13F670A3" },
]
proposal-signing-backend = { type = "Mocked", private-key = "0x0000000000000000000000000000000000000000000000000000000000000001" }

[[evm.hermes.contracts]]
contract = "VAnchor"
address = "0xb824C5F99339C7E486a1b452B635886BE82bc8b7"
deployed-at = 1
size = 0.01
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "athena", address = "0xFEe587E68c470DAE8147B46bB39fF230A29D4769" },
]
proposal-signing-backend = { type = "Mocked", private-key = "0x0000000000000000000000000000000000000000000000000000000000000001" }

[[evm.hermes.contracts]]
contract = "SignatureBridge"
address = "0xDe09E74d4888Bc4e65F589e8c13Bce9F71DdF4c7"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
