[evm.hermes]
http-endpoint = "http://localhost:5001"
ws-endpoint = "ws://localhost:5001"
chain-id = 5001
private-key = "$HERMES_PRIVATE_KEY"
tx-queue = { max-sleep-interval = 1500 }

[[evm.hermes.contracts]]
contract = "Anchor"
address = "0xbfce6B877Ebff977bB6e80B24FbBb7bC4eBcA4df"
deployed-at = 1
size = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "athena", address = "0x4e3df2073bf4b43B9944b8e5A463b1E185D6448C" },
]
proposal-signing-backend = { type = "Mocked", private-key = "0x0000000000000000000000000000000000000000000000000000000000000001" }

[[evm.hermes.contracts]]
contract = "SignatureBridge"
address = "0xDe09E74d4888Bc4e65F589e8c13Bce9F71DdF4c7"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
