[evm.rinkeby]
http-endpoint = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://rinkeby.infura.io/ws/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://rinkeby.etherscan.io"
chain-id = 4
private-key = "$RINKEBY_PRIVATE_KEY"
beneficiary = "0x2222222222222222222222222222222222222222"

[[evm.rinkeby.contracts]]
contract = "Tornado"
address = "0x626FEc5Ffa7Bf1EE8CEd7daBdE545630473E3ABb"
deployed-at = 8896800
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0.05
withdraw-gaslimit = "0x350000"

[[evm.rinkeby.contracts]]
contract = "Anchor"
address = "0x0ab17504465cB1b5235c6b4020A65faf070D5cDA"
deployed-at = 9618040
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x03812879Bc2Cc702956671036463E6873f631786" },
  { chain = "goerli", address = "0x0Aa49a86f526E44853A2704984d6A91C7289Fc93" },
]

[[evm.rinkeby.contracts]]
contract = "Anchor"
address = "0x8431fDec940555becED3f4C04374c1D60b4ac07e"
deployed-at = 9618040
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "goerli", address = "0xD24Eea4f4e17f7a708b2b156D3B90C921659BE80" },
]
