[evm.ropsten]
http-endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://ropsten.etherscan.io"
chain-id = 3
private-key = "$ROPSTEN_PRIVATE_KEY"

[[evm.ropsten.contracts]]
contract = "Anchor"
address = "0x03812879Bc2Cc702956671036463E6873f631786"
deployed-at = 11400390
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "rinkeby", address = "0x0ab17504465cB1b5235c6b4020A65faf070D5cDA" },
  { chain = "goerli", address = "0x0Aa49a86f526E44853A2704984d6A91C7289Fc93" },
]
