[evm.ropsten]
http-endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://ropsten.etherscan.io"
chain-id = 3
private-key = "$ROPSTEN_PRIVATE_KEY"

[[evm.ropsten.contracts]]
contract = "Bridge"
address = "0x0C82Aa5eBCa437C8217cA8b96496625FCD1B476f"
deployed-at = 11308550
events-watcher = { enabled = true, polling-interval = 15000 }

[[evm.ropsten.contracts]]
contract = "Anchor"
address = "0xB039952e6A46b890e2a44835d97dE253482b2Ca2"
deployed-at = 11308550
size = 0.0000000000001
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "rinkeby", address = "0x33EAD0AE289f172E00BDD2e5c39BDF5b18F9d63A" },
  { chain = "goerli", address = "0x19b72e48a90975a5B9F88C5ae907607A13bf827A" },
]