[evm.ropsten]
http-endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://ropsten.etherscan.io"
chain-id = 3
private-key = "$ROPSTEN_PRIVATE_KEY"

[[evm.ropsten.contracts]]
contract = "Bridge"
address = "0x5D755FF247Ba6c588386b15fE29D04B1DcaC0124"
deployed-at = 11342930
events-watcher = { enabled = true, polling-interval = 15000 }

[[evm.ropsten.contracts]]
contract = "Anchor"
address = "0x0711Ea63FDEDD2c8a9d3C9340a5A8F6cd84b6A92"
deployed-at = 11342930
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "rinkeby", address = "0x15A66977f0A9D21e09eB6C1B42b001aF992f0C8f" },
  { chain = "goerli", address = "0x025348e15e9d5529E5A4A55E8eA7eC923b7fB8b6" },
]