[substrate.dkglocal]
http-endpoint = "http://localhost:9933/"
ws-endpoint = "ws://localhost:9944/"
runtime = "DKG"
suri = "//Charlie"

[[substrate.dkglocal.pallets]]
pallet = "DKGProposals"
events-watcher = { enabled = true, polling-interval = 3000 }
