[evm.hermes]
http-endpoint = "http://localhost:5001"
ws-endpoint = "ws://localhost:5001"
explorer = "https://rinkeby.etherscan.io"
chain-id = 5001
private-key = "$HERMES_PRIVATE_KEY"

[[evm.hermes.contracts]]
contract = "AnchorOverDKG"
dkg-node = "dkglocal"
address = "0xD30C8839c1145609E564b986F667b273Ddcb8496"
deployed-at = 1
size = 1
events-watcher = { enabled = true, polling-interval = 7000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "athena", address = "0xe69a847CD5BC0C9480adA0b339d7F0a8caC2B667" },
]

[[evm.hermes.contracts]]
contract = "Bridge"
address = "0xDe09E74d4888Bc4e65F589e8c13Bce9F71DdF4c7"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 7000 }
