[evm.arbitrumtestnet]
http-endpoint = <ARBITRUM_TESTNET_HTTPS_API_KEY>
ws-endpoint = <ARBITRUM_TESTNET_WSS_API_KEY>
explorer = "https://rinkeby-explorer.arbitrum.io/#/"
chain-id = 421611
private-key = "$ARBITRUMTESTNET_PRIVATE_KEY"

[[evm.arbitrumtestnet.contracts]]
contract = "Anchor"
address = "0x30aEF9a80BAe60Cd789904C8875fbd6a19b80488"
deployed-at = 11799624
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x09d2D6520BE3922549c81885477258F41c96c43f" },
  { chain = "goerli", address = "0x6188F18359250f241e2171BAFD57447F8931176e" },
  { chain = "polygontestnet", address = "0x95E2eB4c9Fe2FB580E27dCe997e0E3D69FFdDf5a" },
  { chain = "optimismtestnet", address = "0x27a693cdF40acFc18195C2ecc9f0352452624e84" },
  { chain = "rinkeby", address = "0x95E2eB4c9Fe2FB580E27dCe997e0E3D69FFdDf5a" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.arbitrumtestnet.contracts]]
contract = "SignatureBridge"
address = "0xffd2174417a81ea7ac8bea1b8e64f233eeb63084"
deployed-at = 11697042
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
