[evm.arbitrumtestnet]
http-endpoint = <ARBITRUM_TESTNET_HTTPS_API_KEY>
ws-endpoint = <ARBITRUM_TESTNET_WSS_API_KEY>
explorer = "https://rinkeby-explorer.arbitrum.io/#/"
chain-id = 421611
private-key = "$ARBITRUMTESTNET_PRIVATE_KEY"

[[evm.arbitrumtestnet.contracts]]
contract = "Anchor"
address = "0x2D21BC3f8cb399d3b7091309AFe1986cdB9F2e39"
deployed-at = 11938915
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x228aC202fB6Ad3D3A39f59E4A578a0EAFD3286CD" },
  { chain = "rinkeby", address = "0xa238c5987142AF720B9232d9d72A12A3868396e0" },
  { chain = "goerli", address = "0x03b88eD9Ff9bE84e4baD3F55D67AE5ABA610523C" },
  { chain = "polygontestnet", address = "0xA8665042EA4767FA09143bd790059cE53Bdf2a8F" },
  { chain = "optimismtestnet", address = "0x09d2D6520BE3922549c81885477258F41c96c43f" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.arbitrumtestnet.contracts]]
contract = "SignatureBridge"
address = "0xffd2174417a81ea7ac8bea1b8e64f233eeb63084"
deployed-at = 11938915
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
