[evm.arbitrumtestnet]
http-endpoint = "$ARBITRUM_HTTPS_ALCHEMY_KEY"
ws-endpoint = "$ARBITRUM_WSS_ALCHEMY_KEY"
explorer = "https://rinkeby-explorer.arbitrum.io/#/"
chain-id = 421611
private-key = "$ARBITRUMTESTNET_PRIVATE_KEY"

[[evm.arbitrumtestnet.contracts]]
contract = "Anchor"
address = "0x151bb411B44088a4615A1314B5a948272d8A0342"
deployed-at = 11721072
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0xC95ffc094b31789f5F1a6cbaE071d7cc6e677d19" },
  { chain = "goerli", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "polygontestnet", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "optimismtestnet", address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819" },
  { chain = "rinkeby", address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.arbitrumtestnet.contracts]]
contract = "SignatureBridge"
address = "0xffd2174417a81ea7ac8bea1b8e64f233eeb63084"
deployed-at = 11697042
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
