[evm.arbitrumtestnet]
http-endpoint = "https://arb-rinkeby.g.alchemy.com/v2/$ALCHEMY_KEY"
ws-endpoint = "wss://arb-rinkeby.g.alchemy.com/v2/$ALCHEMY_KEY"
explorer = "https://rinkeby-explorer.arbitrum.io/#/"
chain-id = 421611
private-key = "$ARBITRUMTESTNET_PRIVATE_KEY"

[[evm.arbitrumtestnet.contracts]]
contract = "Anchor"
address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9"
deployed-at = 8301075
size = 0.1
events-watcher = { enabled = true, polling-interval = 5000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "goerli", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "polygontestnet", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "optimismtestnet", address = "0x2a80c1ef363c4dfadce2e0bb6094fae04622a232" },
  { chain = "rinkeby", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }
