[evm.goerli]
http-endpoint = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://goerli.etherscan.io"
chain-id = 5
private-key = "$GOERLI_PRIVATE_KEY"

[[evm.goerli.contracts]]
contract = "Anchor"
address = "0x40f587e4782f4457541c2971d700ebb888262ac7"
deployed-at = 6830257
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "rinkeby", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "polygontestnet", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "optimismtestnet", address = "0x2a80c1ef363c4dfadce2e0bb6094fae04622a232" },
  { chain = "arbitrumtestnet", address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }
