[evm.optimismtestnet]
http-endpoint = "https://kovan.optimism.io"
ws-endpoint = "wss://kovan.optimism.io"
explorer = "https://kovan-optimistic.etherscan.io/"
chain-id = 69
private-key = "$OPTIMISMTESTNET_PRIVATE_KEY"

[[evm.optimismtestnet.contracts]]
contract = "Anchor"
address = "0xC44A4EcAC4f23b6F92485Cb1c90dBEd75a987BC8"
deployed-at = 877902
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x97747a4De7302Ff7Ee3334e33138879469BFEcf8" },
  { chain = "goerli", address = "0x6aA5C74953F7Da1556a298C5e129E417410474E2" },
  { chain = "polygontestnet", address = "0x12323BcABB342096669d80F968f7a31bdB29d4C4" },
  { chain = "rinkeby", address = "0x09B722aA809A076027FA51902e431a8C03e3f8dF" },
  { chain = "arbitrumtestnet", address = "0xD8a8F9629a98EABFF31CfA9493f274A4D5e768Cd" },
]
