[evm.optimismtestnet]
http-endpoint = "$OPTIMISM_HTTPS_ALCHEMY_KEY"
ws-endpoint = "$OPTIMISM_WSS_ALCHEMY_KEY"
explorer = "https://kovan-optimistic.etherscan.io/"
chain-id = 69
private-key = "$OPTIMISMTESTNET_PRIVATE_KEY"

[[evm.optimismtestnet.contracts]]
contract = "Anchor"
address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819"
deployed-at = 2535400
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0xC95ffc094b31789f5F1a6cbaE071d7cc6e677d19" },
  { chain = "goerli", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "polygontestnet", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "rinkeby", address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819" },
  { chain = "arbitrumtestnet", address = "0x151bb411B44088a4615A1314B5a948272d8A0342" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.optimismtestnet.contracts]]
contract = "SignatureBridge"
address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9"
deployed-at = 2498699
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
