[evm.optimismtestnet]
http-endpoint = "https://opt-kovan.g.alchemy.com/v2/$OPTIMISM_ALCHEMY_KEY"
ws-endpoint = "wss://opt-kovan.g.alchemy.com/v2/$OPTIMISM_ALCHEMY_KEY"
explorer = "https://kovan-optimistic.etherscan.io/"
chain-id = 69
private-key = "$OPTIMISMTESTNET_PRIVATE_KEY"

[[evm.optimismtestnet.contracts]]
contract = "Anchor"
address = "0x9c0B0e0Fb6dac561Ad4c947e6Db9abcf0f40B6Dc"
deployed-at = 2522529
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x12f2C4A1469B035e4459539E38ae68bC4DD5ba07" },
  { chain = "goerli", address = "0x9c0B0e0Fb6dac561Ad4c947e6Db9abcf0f40B6Dc" },
  { chain = "polygontestnet", address = "0x84EbBB5F7884C6d71a45C298B1CEaed940E2334E" },
  { chain = "rinkeby", address = "0x12f2C4A1469B035e4459539E38ae68bC4DD5ba07" },
  { chain = "arbitrumtestnet", address = "0x3dd2457c44e79aF992120E817FF4BE22B023e22a" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.optimismtestnet.contracts]]
contract = "SignatureBridge"
address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9"
deployed-at = 2498699
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
