[evm.optimismtestnet]
http-endpoint = "https://kovan.optimism.io"
ws-endpoint = "wss://kovan.optimism.io"
explorer = "https://kovan-optimistic.etherscan.io/"
chain-id = 69
private-key = "$OPTIMISMTESTNET_PRIVATE_KEY"

[[evm.optimismtestnet.contracts]]
contract = "Anchor"
address = "0x2a80c1ef363c4dfadce2e0bb6094fae04622a232"
deployed-at = 2498699
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "goerli", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "polygontestnet", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "rinkeby", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "arbitrumtestnet", address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }
