[evm.optimismtestnet]
http-endpoint = <OPTIMISM_TESTNET_HTTPS_API_KEY>
ws-endpoint = <OPTIMISM_TESTNET_WSS_API_KEY>
explorer = "https://kovan-optimistic.etherscan.io/"
chain-id = 69
private-key = "$OPTIMISMTESTNET_PRIVATE_KEY"

[[evm.optimismtestnet.contracts]]
contract = "Anchor"
address = "0x27a693cdF40acFc18195C2ecc9f0352452624e84"
deployed-at = 2664708
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x09d2D6520BE3922549c81885477258F41c96c43f" },
  { chain = "goerli", address = "0x95E2eB4c9Fe2FB580E27dCe997e0E3D69FFdDf5a" },
  { chain = "polygontestnet", address = "0x6188F18359250f241e2171BAFD57447F8931176e" },
  { chain = "rinkeby", address = "0x95E2eB4c9Fe2FB580E27dCe997e0E3D69FFdDf5a" },
  { chain = "arbitrumtestnet", address = "0x30aEF9a80BAe60Cd789904C8875fbd6a19b80488" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.optimismtestnet.contracts]]
contract = "SignatureBridge"
address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9"
deployed-at = 2498699
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
