[evm.polygontestnet]
http-endpoint = "https://rpc-mumbai.maticvigil.com/v1/$MATICVIGIL_KEY"
ws-endpoint = "wss://rpc-mumbai.maticvigil.com/ws/v1/$MATICVIGIL_KEY"
explorer = "https://mumbai.polygonscan.com/"
chain-id = 80001
private-key = "$POLYGONTESTNET_PRIVATE_KEY"

[[evm.polygontestnet.contracts]]
contract = "Anchor"
address = "0x40f587e4782f4457541c2971d700ebb888262ac7"
deployed-at = 26201873
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "rinkeby", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "goerli", address = "0x40f587e4782f4457541c2971d700ebb888262ac7" },
  { chain = "optimismtestnet", address = "0x2a80c1ef363c4dfadce2e0bb6094fae04622a232" },
  { chain = "arbitrumtestnet", address = "0xfbda54512c6aa9a6bc790f11585aff170d393ee9" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }
