[evm.polygontestnet]
http-endpoint = "https://polygon-mumbai.g.alchemy.com/v2/$POLYGON_ALCHEMY_KEY"
ws-endpoint = "wss://polygon-mumbai.g.alchemy.com/v2/$POLYGON_ALCHEMY_KEY"
explorer = "https://mumbai.polygonscan.com/"
chain-id = 80001
private-key = "$POLYGONTESTNET_PRIVATE_KEY"

[[evm.polygontestnet.contracts]]
contract = "Anchor"
address = "0x84EbBB5F7884C6d71a45C298B1CEaed940E2334E"
deployed-at = 26218757
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x12f2C4A1469B035e4459539E38ae68bC4DD5ba07" },
  { chain = "rinkeby", address = "0x12f2C4A1469B035e4459539E38ae68bC4DD5ba07" },
  { chain = "goerli", address = "0x9c0B0e0Fb6dac561Ad4c947e6Db9abcf0f40B6Dc" },
  { chain = "optimismtestnet", address = "0x9c0B0e0Fb6dac561Ad4c947e6Db9abcf0f40B6Dc" },
  { chain = "arbitrumtestnet", address = "0x3dd2457c44e79aF992120E817FF4BE22B023e22a" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.polygontestnet.contracts]]
contract = "SignatureBridge"
address = "0xc11a9f2f42cedf687ec292231698a91dd6928d9a"
deployed-at = 26201900
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
