[evm.polygontestnet]
http-endpoint = "https://rpc-mumbai.maticvigil.com/v1/$MATICVIGIL_KEY"
ws-endpoint = "wss://rpc-mumbai.maticvigil.com/ws/v1/$MATICVIGIL_KEY"
explorer = "https://mumbai.polygonscan.com/"
chain-id = 80001
private-key = "$POLYGONTESTNET_PRIVATE_KEY"

[[evm.polygontestnet.contracts]]
contract = "Anchor"
address = "0x12323BcABB342096669d80F968f7a31bdB29d4C4"
deployed-at = 23781159
size = 0.1
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "ropsten", address = "0x97747a4De7302Ff7Ee3334e33138879469BFEcf8" },
  { chain = "rinkeby", address = "0x09B722aA809A076027FA51902e431a8C03e3f8dF" },
  { chain = "goerli", address = "0x6aA5C74953F7Da1556a298C5e129E417410474E2" },
  { chain = "optimismtestnet", address = "0xC44A4EcAC4f23b6F92485Cb1c90dBEd75a987BC8" },
  { chain = "arbitrumtestnet", address = "0xD8a8F9629a98EABFF31CfA9493f274A4D5e768Cd" },
]
