[evm.ropsten]
http-endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://ropsten.etherscan.io"
chain-id = 3
private-key = "$ROPSTEN_PRIVATE_KEY"

[[evm.ropsten.contracts]]
contract = "Anchor"
address = "0x228aC202fB6Ad3D3A39f59E4A578a0EAFD3286CD"
deployed-at = 12270712
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "rinkeby", address = "0xa238c5987142AF720B9232d9d72A12A3868396e0" },
  { chain = "goerli", address = "0x03b88eD9Ff9bE84e4baD3F55D67AE5ABA610523C" },
  { chain = "polygontestnet", address = "0xA8665042EA4767FA09143bd790059cE53Bdf2a8F" },
  { chain = "optimismtestnet", address = "0x09d2D6520BE3922549c81885477258F41c96c43f" },
  { chain = "arbitrumtestnet", address = "0x2D21BC3f8cb399d3b7091309AFe1986cdB9F2e39" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.ropsten.contracts]]
contract = "SignatureBridge"
address = "0xc11a9f2f42cedf687ec292231698a91dd6928d9a"
deployed-at = 12270712
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
