[evm.ropsten]
http-endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
ws-endpoint = "wss://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
explorer = "https://ropsten.etherscan.io"
chain-id = 3
private-key = "$ROPSTEN_PRIVATE_KEY"

[[evm.ropsten.contracts]]
contract = "Anchor"
address = "0xC95ffc094b31789f5F1a6cbaE071d7cc6e677d19"
deployed-at = 12242400
size = 0.01
events-watcher = { enabled = true, polling-interval = 15000 }
withdraw-fee-percentage = 0
withdraw-gaslimit = "0x350000"
linked-anchors = [
  { chain = "rinkeby", address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819" },
  { chain = "goerli", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "polygontestnet", address = "0x3e8B7e3B498eA9375172f4d4bd181C21f18A4381" },
  { chain = "optimismtestnet", address = "0xf2f7bc0bED36d94c19C337b6E114caD2bC218819" },
  { chain = "arbitrumtestnet", address = "0x151bb411B44088a4615A1314B5a948272d8A0342" },
]
proposal-signing-backend = { type = "Mocked", private-key = "$GOVERNOR_PRIVATE_KEY" }

[[evm.ropsten.contracts]]
contract = "SignatureBridge"
address = "0xc11a9f2f42cedf687ec292231698a91dd6928d9a"
deployed-at = 12240700
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
