# Block which represents properties for a network
[cosmwasm.juno]
# The name that the chain is indexed on, for linkable anchors
name = "localjuno"
# Http(s) Endpoint for quick Req/Res
http-endpoint = "http://localhost:26657"
# Websocket Endpoint for long living connections
ws-endpoint = "ws://localhost:26657"
# chain id
chain-id = "testing"

# The mnemonic of this account on network
mnemonic = "clip hire initial neck maid actor venue client foam budget lock catalog sweet steak waste crater broccoli pipe steak sister coyote moment obvious choose"

tx-queue = { max-sleep-interval = 1500 }
# Value to indicate that the relayer should enable services for this chain
enabled = true

# Block which represents the configuration for a supported contract on the network
[[cosmwasm.juno.contracts]]
# The contract can be one of these values
# - VAnchor (Variable Anchor)
# - SignatureBridge
contract = "VAnchor"
# The address of the contract
address = "juno1l9neq7e5e9l48nwx9287u7f7lrq3jv5ejwuv52zxgwy6c49h2wlsgqa90h"
# The deployed block number of the contract. When a relayer does not have information for
# this contract in its store, it will start to sync and query for relevant historical data
# starting at this block number
deployed-at = 1
# Configuration for the events watcher of this contract. The events-watcher can be switched on/off
# and the polling interval specifies the period of time (in ms) that the events-watcher thread
# will wait before issuing another query for new events.
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
# Configuration related to withdraw (for private transaction relaying)
#    - withdraw-gasLimit: Value which specifies the maximum amount of gas which will be used when
#                         submitting a withdraw transaction
#    - withdraw-fee-percentage: Value which specifies the fees that this relayer will collect upon
#                               submitting a withdraw transaction
withdraw-config = { withdraw-fee-percentage = 0, withdraw-limit = "0" }
# Entries for this anchor contract's connected edges.
# These fields are used to determine the generation of AnchorUpdate proposals
linked-anchors = [
  { chain = "localterra", address = "terra1679n3rthcvghet6tc29ugqtn5f3axp0lvceshq0c0r482pps3u4qggfyax" },
]
# Proposal signing backend can have a value of "Mocked" or the name of the DKG configuration.
# When the type is "Mocked", the supplied private-key will sign any proposed updates and submit
# the signed proposals to the configured SignatureBridge of the relevant chains.
proposal-signing-backend = { type = "Mocked", private-key = "0x0000000000000000000000000000000000000000000000000000000000000001" }

[[cosmwasm.juno.contracts]]
contract = "SignatureBridge"
address = "juno1l9neq7e5e9l48nwx9287u7f7lrq3jv5ejwuv52zxgwy6c49h2wlsgqa90h"
deployed-at = 1
events-watcher = { enabled = true, polling-interval = 10000, print-progress-interval = 0 }
