{
 "title": "Relayer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total fee earned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_fee_earned / 10^18", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gas spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gas_spent / 10^18", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chain account balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "chain_account_balance / 10 ^ 9", "legendFormat": "{{chain_type}}({{chain_id}})" }
   ]
  },
  {
   "title": "Anchor update proposals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "anchor_update_proposals", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Resource total fees earned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "resource_total_fees_earned / 10 ^ 18",
     "legendFormat": "{{chain_type}}({{chain_id}}) {{target_system_type}}({{target_system_value}})"
    }
   ]
  },
  {
   "title": "Queue backoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "evm_transaction_queue_back_off", "legendFormat": "{{__name__}}" },
    {
     "expr": "substrate_transaction_queue_back_off",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "transaction_queue_back_off", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Resource total gas spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "resource_total_gas_spent / 10^9",
     "legendFormat": "{{chain_type}}({{chain_id}}) {{target_system_type}}({{target_system_value}})"
    }
   ]
  },
  {
   "title": "Bridge Watcher Backoff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "bridge_watcher_back_off", "legendFormat": "{{__name__}}" },
    {}
   ]
  },
  {
   "title": "Total amount of data stored",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_amount_of_data_stored", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proposals signed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proposals_signed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proposals processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "proposals_processed_evm_tx_queue",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "proposals_processed_substrate_tx_queue",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "proposals_processed_tx_queue", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}