name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

  workflow_dispatch:
env:
  DEV_PACKAGES: build-essential musl musl-dev musl-tools pkg-config libssl-dev librust-openssl-sys-dev libc6
  ETH1_INFURA_API_KEY: ${{ secrets.ETH1_INFURA_API_KEY }}

jobs:

  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
          
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: ${{ matrix.target }}

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.target }} --features native-tls/vendored --locked
          command: build

    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - x86_64-apple-darwin

  macos-unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
          
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: ${{ matrix.target }}

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.target }} --locked
          command: test
          
    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - x86_64-apple-darwin
        

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: install system build dependencies
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install ${DEV_PACKAGES}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.target }} --features native-tls/vendored --locked
          command: build

    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl

  linux-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: install system build dependencies
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install ${DEV_PACKAGES}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "./tests/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./tests/yarn.lock"
          registry-url: "https://npm.pkg.github.com"

      - run: yarn global add @webb-tools/dkg-standalone-binary@latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Env file
        run: |
            touch .env
            echo ETH1_INFURA_API_KEY = ${{ secrets.ETH1_INFURA_API_KEY }} >> .env
          
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.target }} --features native-tls/vendored --locked
          command: test

    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl


  linux-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: install system build dependencies
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install ${DEV_PACKAGES}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "./tests/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./tests/yarn.lock"
          registry-url: "https://npm.pkg.github.com"

        if: matrix.target == 'x86_64-unknown-linux-musl'
      - run: cargo build --features integration-tests,cli,native-tls/vendored
        if: matrix.target == 'x86_64-unknown-linux-musl'
        shell: bash

      - name: Install NPM Packages.
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cd tests && dvc pull && yarn

      - name: Pull Docker Images used for testing.
        run: docker pull ghcr.io/webb-tools/protocol-substrate-standalone-node:stable
        
      - name: Webb Relayer Integration tests.
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cd tests && yarn test

    strategy:
      fail-fast: true
      matrix:
        channel: [stable]
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
