name: Publish Docs

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  publish_docs:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: Publish Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Update apt repositories
        run: sudo apt update

      - name: Build documentation
        run: cargo doc --no-deps 
      - name: Publish documentation
        run: |
          cd target/doc
          git init
          echo '<meta http-equiv="refresh" content="0; url=https://webb-tools.github.io/relayer/webb_relayer/index.html">' > index.html
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation 🚀'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
